[workspace]
name = "azir"
version = "0.1.0"
edition = "2024"
members = [
    "azir_core",
    "azir_cli",
]
resolver = "2"

[workspace.dependencies]
base64 = "0.21"
flate2 = "1.0"
acir = { git = "https://github.com/noir-lang/noir", package = "acir" }
acir_field = { git = "https://github.com/noir-lang/noir", package = "acir_field" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
azir_core = { path = "./azir_core"}
